# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ 2020 ]
  pull_request:
    branches: [ 2020 ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install npm dependencies
      run: npm install
    - name: Run build task
      run: npm run arrudeia
    - name: ftp-action
      uses: sebastianpopp/ftp-action@v2.0.0
      with:
        host: ftp.oncase.com.br
        user: oncasec
        password: k4MHjb9GuE8E3XMv
        forceSsl: false
        localDir: "dist/out/"
        remoteDir: ./home/oncasec/oncase.com.br/public2/
