# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ 2020 ]
  pull_request:
    branches: [ 2020 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install npm dependencies
      run: npm install
    - name: Run build task
      run: npm run arrudeia
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@v2.2.11
      env:
          SSH_PRIVATE_KEY: SHA256:9hI5U6eA86Tjj3liY98CrL/Zj6FHPw1Tu2oTEuVizJo
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "dist/out/"
          REMOTE_HOST: ftp.oncase.com.br
          REMOTE_USER: oncasec
          TARGET: /home/oncasec/oncase.com.br/public2/
